// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtTOodN8DXvh-zu0PZIeHI3NVr1WZJzD8',
    appId: '1:970896066422:web:d00c2a918283b15ededc57',
    messagingSenderId: '970896066422',
    projectId: 'spread-edfc6',
    authDomain: 'spread-edfc6.firebaseapp.com',
    storageBucket: 'spread-edfc6.appspot.com',
    measurementId: 'G-29YDL0MV2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcwMUqXSUhyiWNhml4L35hsudlaWs4A30',
    appId: '1:970896066422:android:8568d6d19729557ededc57',
    messagingSenderId: '970896066422',
    projectId: 'spread-edfc6',
    storageBucket: 'spread-edfc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOazgtMNxCiu8KUy03OgCsAEegFkBttVY',
    appId: '1:970896066422:ios:f8e8e35907e28836dedc57',
    messagingSenderId: '970896066422',
    projectId: 'spread-edfc6',
    storageBucket: 'spread-edfc6.appspot.com',
    iosBundleId: 'com.example.spread',
  );
}
